create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  category_preference text null,
  created_at timestamptz not null default now(),
  is_active boolean not null default true
);

create unique index if not exists subscribers_email_unique_idx
  on public.subscribers (lower(email));

alter table public.subscribers
  add constraint subscribers_email_unique
  unique using index subscribers_email_unique_idx;